### PR TITLE
Milestone 5 UI PR to Development

### PR DESCRIPTION
**Pull request by redacuve**
This PR contains all of the milestone 5 requirements "UI".

- The Elements of the design have been identified and applied to the components.
- The features that haven't implemented yet have their own placeholders (e.g. “Comments” link or “% completed”).
- Implemented style of the different components based on the design.
- Each element looks exactly the same as in the design.
- Added responsiveness to the design, it's mobile-friendly.

The buttons that work are only the remove under the book title and the save book in the form component.

live version here: https://bookstore-cms-react-and-redux.herokuapp.com/

### CODE REVIEW

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

* [ ] Styling should be **EXACTLY** the same as the one provided in the designs ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone5/exactlySameAsDesign.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/45791599/))
  - The navbar has no background.
  - The background is not well distributed as shown in the design.
  - The whole content is not well centered to fit the design.
  - The profile image on the right side of the navbar is absent.
  - The left and right alignment are not as shown in the design.
  - _and any other missing stuff you see as well._

**Note:** I used your online version to review the design, perhaps, you haven't pushed your styling to the live demo?

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

**Comment by redacuve** [comment]
Can you be more clearly (maybe with screenshoots?)  i'm confused

**Comment by suretrust** [comment]
I believe it's quite obvious but kindly check images below if it helps. If you compare them using my comments above, you should easily get a grasp of each comment.

## Your design
Screenshot 2020-08-09 at 10 01 56

## Design given
Screenshot 2020-08-09 at 10 03 40

**Review by bellom — APPROVED** [review]
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
